2022-12-28 04:06:04,533 - [INFO] { logger: main.7; place: start_server.main:6 } Starting server..
2022-12-28 04:06:04,533 - [INFO] { logger: main.7; place: server.__init__:36 } Initializing sockets...
2022-12-28 04:06:04,534 - [INFO] { logger: main.7; place: server._init_sockets:171 } TCP Server created on address: 192.168.1.104:9090
2022-12-28 04:06:04,534 - [INFO] { logger: main.7; place: server._init_sockets:173 } UDP Server created on address: 192.168.1.104:9091
2022-12-28 04:06:04,535 - [INFO] { logger: main.7; place: server.__init__:45 } Found existing folder for files - storage
2022-12-28 04:06:07,513 - [INFO] { logger: main.7; place: server.work:73 } Got new TCP connection <socket.socket fd=364, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.104', 9090)>
2022-12-28 04:06:07,515 - [INFO] { logger: main.7; place: server._initialize_client:200 } New connection initialized - ('192.168.1.104', 21914); 
2022-12-28 04:06:11,664 - [INFO] { logger: main.7; place: command_builder.build_command:22 } Issued TCP command - UPLOAD
2022-12-28 04:06:11,665 - [INFO] { logger: main.7; place: upload_command.__init__:26 } Downloading File storage\storage\img.jpg
2022-12-28 04:06:11,667 - [CRITICAL] { logger: main.7; place: server.work:159 } Unexpected error caught! 
